### PR TITLE
feat: add check/dry run param

### PR DESCRIPTION
**Pull request by minademian**
Hi, first time contributing to this repo and first PR ever submitted to an open-source project.

Thanks for this great tool. I was looking for this use case yesterday, while integrating this library in my project at work.

Have written tests and they have passed.

### CODE REVIEW

**Comment by minademian** [comment]
@shaharke are you still actively maintaining this repo?

**Comment by shaharke** [comment]
No. I’m happy to add a primary maintainer if anyone is up to the task.

**Comment by minademian** [comment]
I'd be interested.

**Comment by shaharke** [comment]
@minademian added you as a collaborator

**Comment by minademian** [comment]
@macobo @deployable @nikolovivan I don't have access to Travis CI, I'm not sure why the build failed. Could you help at all?

**Comment by shaharke** [comment]
> @macobo @deployable @nikolovivan I don't have access to Travis CI, I'm not sure why the build failed. Could you help at all?

@minademian the access is public and you can use your Github account to login.

**Comment by minademian** [comment]
figured it out. the `.travis.yml` file is referencing a really old version of Node. will close this PR and re-submit as a PR on this repo, rather than from my fork.

**Comment by shaharke** [comment]
@minademian notice that if you intend to start using arrow functions in the code base you should bump the minor version of the package and document the fact that we no longer support Node.JS below version 8 (I think it's 8...).

**Comment by minademian** [comment]
@shaharke good note, i'll keep that in mind. no plans as such right now. immediate goals are to familiarize myself with codebase and the release cycle

**Pull request closed without merging**
