### PR TITLE
Generate json for playbook variables paramaters

### PR DESCRIPTION
**Pull request by deployable**
Move `variables` to use JSON.stringify
Modify simple test to use json
Add complex variable test

https://github.com/shaharke/node-ansible/issues/13

### CODE REVIEW

**Comment by shaharke** [comment]
I agree it is simpler, but I feel that the key=value syntax is much more readable. Most of the time that won't matter because you'll probably be using an job server, but for debugging that might be a pain.

**Comment by deployable** [comment]
Fair enough. I still need a way to dump in complex variables and I can't think of a way to make the JSON optional, other than some hacky detection code. It could possibly use a separate function for complex variables but that seems like an ugly solution and might confuse users (i.e. which variable function do I use?)

Also on the debug front, have you seen https://github.com/visionmedia/debug before? I find it super useful and as I use it everywhere would be handy to plug in here. Might solve the debugging vars issue as you could inspect the pretty printed variables themselves before the awkward JSON string in the command output.

**Comment by shaharke** [comment]
You know what... I changed my mind. It's a small price to pay for support in complex variables.

**Comment by shaharke** [comment]
@deployable published

**Comment by deployable** [comment]
Thanks :punch:

**Pull request merged**
